### ISSUE TITLE
Write Schedule for a Day, a Week, or a Month

### ISSUE THREAD

**Issue by hamhead1005** [Andr3wD/CS3560-Team2-PSS#10]
The user can ask for PSS to write a schedule for a particular day, a week, or a
month.
● The user enters a file name and the start date of the time period.
● PSS will then write all of the tasks for that time period, in sorted order, to the
JSON-formatted output file.
● Note that if there is an anti-task, both it and the recurring task instance it
cancels will not be included in the list.
● A recurring task will not be displayed as a single entry. Rather, each instance
of the recurring task that appears in the time period will be displayed.
● The format matches that of the schedule file, except that all of the transient
tasks or recurring instances will appear using the transient task format.

**Comment by Andr3wD** [comment]
Done
