### ISSUE TITLE
Modify edittask to keep task name and type, maybe?

### ISSUE THREAD

**Issue by Andr3wD** [Andr3wD/CS3560-Team2-PSS#19]
It might not make much sense to have every value be modified.

**Comment by mchiemn** [comment]
If the user doesn't want an attribute to be modified, then they would enter the same value. By prompting them for an edit in each one, it gives a wider range of editing capabilities.
Also from the project presentation:
○ The editor displays the current attribute values for the task.
○ Upon submission of any edits, PSS will verify that all of the new attribute values are
acceptable.
Those attributes include, for transient task for example (also from the slides): 
○ Name
○ Type
○ Date
○ StartTime
○ Duration

**Comment by Andr3wD** [comment]
Ah.. I didn't read go over the project requirements. That makes sense. My bad.
