### ISSUE TITLE
Read the Schedule from a file

### ISSUE THREAD

**Issue by hamhead1005** [Andr3wD/CS3560-Team2-PSS#8]
When the user runs this command, PSS asks the user for a file name.
● The program verifies that a file with that name exists.
● This file should hold a valid schedule in JSON format.
● PSS will read each task from the file, adding that task to the schedule.
● However:
○ If there is ANY error in the file, then the read is terminated, and all changes to the schedule
are removed. The changes are only accepted if there are no errors.
○ If the syntax of the file is not value JSON, this would be an error.
○ If any of the tasks given in the file have invalid or inconsistent values, this would be an error.
○ If any tasks would overlap after reading the file, this would be an error.

**Comment by Andr3wD** [comment]
Done
